In [1]:
import os
import pandas as pd

In [2]:
zoc_df = pd.read_csv("/kaggle/input/zocdoc/zocdoc_finalised.csv")
dac_df = pd.read_csv("/kaggle/input/zocdoc/dac_finalised.csv", low_memory=False)

In [3]:
zoc_df["facility_address"] = zoc_df["facility_address"].fillna(zoc_df["street_address"])

zoc_df["cred"] = zoc_df["name"].apply(lambda x: x.split(",")[1].strip() 
                                      if len(x.split(",")) > 1 else None)

zoc_df["name"] = zoc_df["name"].apply(lambda x: x.split(",")[0].strip())

zoc_df = zoc_df[['name', 'cred', 'job_title', 'facility_name', 'facility_address', 'address_locality', 
                 'region', 'postal_code', 'is_dr', 'is_nurse', 'is_assistant']]

In [4]:
dac_df = dac_df.rename(columns={'street_address': 'facility_address'})

dac_df = dac_df[['name', 'cred', 'job_title', 'facility_name', 'facility_address', 'address_locality', 
                 'region', 'postal_code', 'is_dr', 'is_nurse', 'is_assistant']]

In [9]:
print(zoc_df.shape)

zoc_df.head()

(2249, 11)

,name,cred,job_title,facility_name,facility_address,address_locality,region,postal_code,is_dr,is_nurse,is_assistant
0,dr. david bolon,md,cardiologist,parsons smile center,"parsons smile center, 133, east 58th street",new york,NY,10022,1,0,0
1,dr. anil gupta,md,cardiologist,NaN,"1314, hooper avenue, brick township",toms river,NJ,8753,1,0,0
2,dr. fadi a elatat,md,cardiologist,NaN,"facv consultants pc-montclair - 127 pine st, s...",montclair,NJ,7042,1,0,0
3,dr. stephen sherer,md,cardiologist,NaN,"714, bergen boulevard, ridgefield",ridgefield,NJ,7657,1,0,0
4,dr. fadi a elatat,md,cardiologist,NaN,"facv consultants pc-union - 1945 morris ave, s...",union,NJ,7083,1,0,0

In [10]:
print(dac_df.shape)

dac_df.head()

(175854, 11)

,name,cred,job_title,facility_name,facility_address,address_locality,region,postal_code,is_dr,is_nurse,is_assistant
0,jeffrey s kezis,md,dermatologist,"hudson dermatology, pc",969 main st suite d,fishkill,NY,125241791,1,0,0
1,jeffrey s kezis,md,dermatologist,"hudson dermatology, pc",29 fox st fl 4,poughkeepsie,NY,126014732,1,0,0
2,alice kathleen roberts,md,obgyn,regional womens health group llc,1245 highland ave suite 404,abington,PA,190013725,1,0,0
3,michael n sanchez,pt,phy_therapist,innovative physical therapy and fitness of del...,1009 mattlind way suite 200,milford,DE,199635369,0,0,0
4,jung h hahn,md,neurosurgeon,NaN,75 briarcliff rd,staten island,NY,103052620,1,0,0

In [11]:
merged = pd.concat([zoc_df, dac_df])

print(merged.shape)

merged.head()

(178103, 11)

,name,cred,job_title,facility_name,facility_address,address_locality,region,postal_code,is_dr,is_nurse,is_assistant
0,dr. david bolon,md,cardiologist,parsons smile center,"parsons smile center, 133, east 58th street",new york,NY,10022,1,0,0
1,dr. anil gupta,md,cardiologist,NaN,"1314, hooper avenue, brick township",toms river,NJ,8753,1,0,0
2,dr. fadi a elatat,md,cardiologist,NaN,"facv consultants pc-montclair - 127 pine st, s...",montclair,NJ,7042,1,0,0
3,dr. stephen sherer,md,cardiologist,NaN,"714, bergen boulevard, ridgefield",ridgefield,NJ,7657,1,0,0
4,dr. fadi a elatat,md,cardiologist,NaN,"facv consultants pc-union - 1945 morris ave, s...",union,NJ,7083,1,0,0

In [12]:
merged.to_csv("merged.csv")